---

- name: Install zsh in Debian derivatives
  sudo: no
  apt: pkg=zsh state=present
  when: ansible_os_family == 'Debian'

- name: Install git in Debian derivatives
  sudo: no
  apt: pkg=git state=present
  when: ansible_os_family == 'Debian'

- name: Install oh-my-zsh
  git: repo=https://github.com/robbyrussell/oh-my-zsh dest=~/.oh-my-zsh
  sudo: no

- name: Copy .zshrc to $HOME
  sudo: no
  template:
    src: zshrc.j2
    dest: ~/.zshrc

- name: switch to ZSH
  user: name=root shell=/usr/bin/zsh
  sudo: no
  when: ansible_os_family != 'Darwin'

- name: Switch to ZSH (OSX)
  command: chsh -s /bin/zsh
  sudo: no
  when: ansible_os_family == 'Darwin'
